import type { DeckProject } from '../domain/deck';

// 新規デッキの安全テンプレート(果物/野菜)。
// 3グループ役×3種のシンプル構成。ユーザーはここから編集して育てる。
export function createDeckTemplate(id: string, name: string): DeckProject {
  const fruit = [
    ['apple', 'リンゴ', 'リ', '🍎'],
    ['banana', 'バナナ', 'バ', '🍌'],
    ['grape', 'ブドウ', 'ブ', '🍇'],
    ['peach', 'モモ', 'モ', '🍑'],
    ['melon', 'メロン', 'メ', '🍈'],
    ['cherry', 'サクランボ', 'サ', '🍒'],
  ] as const;
  const veg = [
    ['carrot', 'ニンジン', 'ニ', '🥕'],
    ['tomato', 'トマト', 'ト', '🍅'],
    ['onion', 'タマネギ', 'タ', '🧅'],
    ['potato', 'ジャガイモ', 'ジ', '🥔'],
    ['corn', 'トウモロコシ', 'ウ', '🌽'],
    ['pumpkin', 'カボチャ', 'カ', '🎃'],
  ] as const;
  return {
    version: 1,
    id,
    name,
    description: '新しいデッキ。名前・説明・役の点数を編集できます。',
    categories: [
      { id: 'fruit', name: '果物', color: '#EF4444', priority: 80, icon: '🍎' },
      { id: 'veg', name: '野菜', color: '#22C55E', priority: 70, icon: '🥕' },
    ],
    tiles: [
      ...fruit.map(([tileId, tileName, label, emoji]) => ({
        id: tileId,
        name: tileName,
        categories: ['fruit'],
        primaryCategoryId: 'fruit',
        emoji,
        fallbackLabel: label,
        count: 3,
      })),
      ...veg.map(([tileId, tileName, label, emoji]) => ({
        id: tileId,
        name: tileName,
        categories: ['veg'],
        primaryCategoryId: 'veg',
        emoji,
        fallbackLabel: label,
        count: 3,
      })),
    ],
    activeVariantId: 'normal',
    variants: [
      {
        id: 'normal',
        name: '通常版',
        label: '通常版',
        ruleConfig: {
          id: 'normal-three-groups',
          name: '3グループ通常ルール',
          evaluationMode: 'normalThreeGroups',
          supportedPlayerCounts: [3, 4],
          handSizeNormal: 8,
          handSizeAfterDraw: 9,
          winHandSize: 9,
          groupSize: 3,
          groupCount: 3,
          allowRon: true,
          allowPon: false,
          allowKan: false,
          allowChi: false,
          allowReach: false,
          allowScoreBonus: true,
          allowWildcard: true,
        },
        scoreBudget: {
          expectedBaseMin: 30,
          expectedBaseMax: 130,
          expectedResultMin: 40,
          expectedResultMax: 220,
          softResultCap: 300,
          hardResultCap: 500,
          maxSpecialBonusTotal: 80,
          maxScoreBonusTotal: 60,
        },
        winRoles: [
          {
            id: 'win_fruit_three_groups',
            name: 'くだもの畑',
            kind: 'win_role',
            family: 'groupPattern',
            basePoints: 60,
            requiredGroups: [{ groupType: 'sameCategory', categoryId: 'fruit', count: 3 }],
            allowWildcard: true,
            maxWildcards: 1,
            priority: 10,
            explanation: '果物の3枚グループを3組そろえる。',
            canTsumo: true,
            canRon: true,
          },
          {
            id: 'win_veg_three_groups',
            name: 'やさい畑',
            kind: 'win_role',
            family: 'groupPattern',
            basePoints: 60,
            requiredGroups: [{ groupType: 'sameCategory', categoryId: 'veg', count: 3 }],
            allowWildcard: true,
            maxWildcards: 1,
            priority: 20,
            explanation: '野菜の3枚グループを3組そろえる。',
            canTsumo: true,
            canRon: true,
          },
          {
            id: 'win_mixed_field',
            name: 'まぜこぜ畑',
            kind: 'win_role',
            family: 'groupPattern',
            basePoints: 80,
            requiredGroups: [
              { groupType: 'sameCategory', categoryId: 'fruit', count: 1 },
              { groupType: 'sameCategory', categoryId: 'veg', count: 2 },
            ],
            allowWildcard: true,
            maxWildcards: 1,
            priority: 30,
            explanation: '果物グループ1組と野菜グループ2組をそろえる。',
            canTsumo: true,
            canRon: true,
          },
        ],
        specialBonuses: [],
        scoreBonuses: [],
      },
    ],
  };
}
